name: Run Tests & Code Coverage
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      # Add test server as a service
      test-server:
        image: python:3.8-slim
        ports:
          - 4711:4711
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'
          
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mcpi
          pip install ollama
          pip install pytest pytest-cov
          
      - name: Start Test Server
        run: |
          python your_server.py &
          echo "Waiting for server to start..."
          sleep 5
          
      - name: Run Tests with Coverage
        env:
          TEST_MODE: 'ci'
          TEST_SERVER_URL: 'http://localhost:4711'
        run: |
          pytest --cov=agents --cov=framework --cov-report=xml
          
      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.xml
          flags: unittests
          name: codecov-minecraft-framework
